name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.platform }}

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_TWEAG_JUPYTER_NIX_AUTH_TOKEN }}

    - name: Check example_jupyterlab
      run: |
        nix build -Lv .#packages.x86_64-linux.example_jupyterlab

    - name: Check Template
      run: |
        nix build -Lv template#packages.x86_64-linux.jupyterEnvironment --override-input jupyterWith ./.

    # - name: Check
    #   run: |
    #     nix flake check --show-trace -L
